FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /usr/src/mymaven
COPY ./ ./
RUN mvn clean install -DskipTests

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY --from=builder /usr/src/mymaven/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]